project_id = "funcommute-e2e"

[api]
enabled = true
port = 55421
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 55422
shadow_port = 55420
major_version = 15

[db.pooler]
enabled = false
port = 55429
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[studio]
enabled = true
port = 55423

[inbucket]
enabled = true
port = 55424
smtp_port = 55425
pop3_port = 55426

[storage]
enabled = true

[auth]
enabled = true

[analytics]
enabled = false
port = 55427
vector_port = 55428

[edge_runtime]
enabled = true
inspector_port = 55430
