CREATE TABLE IF NOT EXISTS public.core_product_migration_quarantine (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_table TEXT NOT NULL,
  source_row_id UUID,
  row_data JSONB NOT NULL,
  reason TEXT NOT NULL,
  archived_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DO $$
DECLARE
  table_name TEXT;
  duplicate_id UUID;
BEGIN
  FOR table_name IN
    SELECT unnest(ARRAY['daily_reports', 'draft_reports', 'notification_settings', 'notification_history'])
  LOOP
    EXECUTE format('UPDATE public.%I SET id = gen_random_uuid() WHERE id IS NULL', table_name);
    FOR duplicate_id IN EXECUTE format(
      'SELECT id FROM public.%I GROUP BY id HAVING count(*) > 1', table_name
    )
    LOOP
      EXECUTE format($sql$
        WITH ranked AS (
          SELECT ctid, row_number() OVER (
            ORDER BY ctid DESC
          ) AS row_number
          FROM public.%I
          WHERE id = $1
        )
        INSERT INTO public.core_product_migration_quarantine(source_table, source_row_id, row_data, reason)
        SELECT %L, t.id, to_jsonb(t), %L
        FROM public.%I t
        JOIN ranked r ON r.ctid = t.ctid
        WHERE r.row_number > 1
      $sql$, table_name, table_name, 'duplicate id', table_name)
      USING duplicate_id;
      EXECUTE format($sql$
        DELETE FROM public.%I t
        USING (
          SELECT ctid FROM (
            SELECT ctid, row_number() OVER (
              ORDER BY ctid DESC
            ) AS row_number
            FROM public.%I
            WHERE id = $1
          ) ranked
          WHERE row_number > 1
        ) duplicate_rows
        WHERE t.ctid = duplicate_rows.ctid
      $sql$, table_name, table_name)
      USING duplicate_id;
    END LOOP;
  END LOOP;
END $$;

DO $$
DECLARE
  table_name TEXT;
BEGIN
  FOR table_name IN
    SELECT unnest(ARRAY['daily_reports', 'draft_reports', 'notification_settings', 'notification_history'])
  LOOP
    EXECUTE format($sql$
      INSERT INTO public.core_product_migration_quarantine(source_table, source_row_id, row_data, reason)
      SELECT %L, t.id, to_jsonb(t), %L
      FROM public.%I t
      LEFT JOIN auth.users u ON u.id = t.user_id
      WHERE t.user_id IS NULL OR u.id IS NULL
    $sql$, table_name, 'missing or orphaned user_id', table_name);
    EXECUTE format($sql$
      DELETE FROM public.%I t
      WHERE t.user_id IS NULL
         OR NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = t.user_id)
    $sql$, table_name);
  END LOOP;
END $$;

INSERT INTO public.core_product_migration_quarantine(source_table, source_row_id, row_data, reason)
SELECT 'daily_reports', id, to_jsonb(t), 'missing or invalid required report fields'
FROM public.daily_reports t
WHERE report_date IS NULL
   OR report_type IS NULL
   OR report_type NOT IN ('morning', 'evening', 'weekly')
   OR user_name_snapshot IS NULL
   OR report_content IS NULL;
DELETE FROM public.daily_reports t
WHERE report_date IS NULL
   OR report_type IS NULL
   OR report_type NOT IN ('morning', 'evening', 'weekly')
   OR user_name_snapshot IS NULL
   OR report_content IS NULL;

INSERT INTO public.core_product_migration_quarantine(source_table, source_row_id, row_data, reason)
SELECT 'notification_history', id, to_jsonb(t), 'missing required notification history fields'
FROM public.notification_history t
WHERE notification_type IS NULL OR title IS NULL OR message IS NULL OR sent_at IS NULL;
DELETE FROM public.notification_history t
WHERE notification_type IS NULL OR title IS NULL OR message IS NULL OR sent_at IS NULL;

UPDATE public.draft_reports
SET report_type = NULL
WHERE report_type IS NOT NULL
  AND report_type NOT IN ('morning', 'evening', 'weekly');

UPDATE public.daily_reports
SET created_at = COALESCE(created_at, NOW()),
    updated_at = COALESCE(updated_at, created_at, NOW())
WHERE created_at IS NULL OR updated_at IS NULL;
UPDATE public.draft_reports
SET created_at = COALESCE(created_at, NOW()),
    updated_at = COALESCE(updated_at, created_at, NOW())
WHERE created_at IS NULL OR updated_at IS NULL;
UPDATE public.notification_settings
SET created_at = COALESCE(created_at, NOW()),
    updated_at = COALESCE(updated_at, created_at, NOW())
WHERE created_at IS NULL OR updated_at IS NULL;
UPDATE public.notification_history
SET sent_at = COALESCE(sent_at, NOW())
WHERE sent_at IS NULL;

DROP TABLE IF EXISTS pg_temp.core_product_settings_merge;
CREATE TEMP TABLE core_product_settings_merge ON COMMIT DROP AS
SELECT user_id,
  (ARRAY_AGG(id ORDER BY updated_at DESC NULLS LAST, created_at DESC NULLS LAST, id DESC))[1] AS keeper_id,
  (ARRAY_AGG(morning_reminder_enabled ORDER BY updated_at DESC NULLS LAST, created_at DESC NULLS LAST, id DESC) FILTER (WHERE morning_reminder_enabled IS NOT NULL))[1] AS morning_reminder_enabled,
  (ARRAY_AGG(morning_reminder_time ORDER BY updated_at DESC NULLS LAST, created_at DESC NULLS LAST, id DESC) FILTER (WHERE morning_reminder_time IS NOT NULL))[1] AS morning_reminder_time,
  (ARRAY_AGG(evening_reminder_enabled ORDER BY updated_at DESC NULLS LAST, created_at DESC NULLS LAST, id DESC) FILTER (WHERE evening_reminder_enabled IS NOT NULL))[1] AS evening_reminder_enabled,
  (ARRAY_AGG(evening_reminder_time ORDER BY updated_at DESC NULLS LAST, created_at DESC NULLS LAST, id DESC) FILTER (WHERE evening_reminder_time IS NOT NULL))[1] AS evening_reminder_time,
  (ARRAY_AGG(weekend_reminders ORDER BY updated_at DESC NULLS LAST, created_at DESC NULLS LAST, id DESC) FILTER (WHERE weekend_reminders IS NOT NULL))[1] AS weekend_reminders,
  (ARRAY_AGG(email_notifications ORDER BY updated_at DESC NULLS LAST, created_at DESC NULLS LAST, id DESC) FILTER (WHERE email_notifications IS NOT NULL))[1] AS email_notifications,
  (ARRAY_AGG(browser_notifications ORDER BY updated_at DESC NULLS LAST, created_at DESC NULLS LAST, id DESC) FILTER (WHERE browser_notifications IS NOT NULL))[1] AS browser_notifications
FROM public.notification_settings
GROUP BY user_id;

INSERT INTO public.core_product_migration_quarantine(source_table, source_row_id, row_data, reason)
SELECT 'notification_settings', s.id, to_jsonb(s), 'duplicate user_id; latest meaningful values merged into retained row'
FROM public.notification_settings s
JOIN core_product_settings_merge m ON m.user_id = s.user_id
WHERE s.id <> m.keeper_id;

DELETE FROM public.notification_settings s
USING core_product_settings_merge m
WHERE s.user_id = m.user_id AND s.id <> m.keeper_id;

UPDATE public.notification_settings s
SET morning_reminder_enabled = COALESCE(m.morning_reminder_enabled, TRUE),
    morning_reminder_time = COALESCE(m.morning_reminder_time, '09:00:00'::TIME),
    evening_reminder_enabled = COALESCE(m.evening_reminder_enabled, TRUE),
    evening_reminder_time = COALESCE(m.evening_reminder_time, '18:00:00'::TIME),
    weekend_reminders = COALESCE(m.weekend_reminders, FALSE),
    email_notifications = COALESCE(m.email_notifications, FALSE),
    browser_notifications = COALESCE(m.browser_notifications, TRUE)
FROM core_product_settings_merge m
WHERE s.id = m.keeper_id
  AND (
    s.morning_reminder_enabled IS DISTINCT FROM COALESCE(m.morning_reminder_enabled, TRUE)
    OR s.morning_reminder_time IS DISTINCT FROM COALESCE(m.morning_reminder_time, '09:00:00'::TIME)
    OR s.evening_reminder_enabled IS DISTINCT FROM COALESCE(m.evening_reminder_enabled, TRUE)
    OR s.evening_reminder_time IS DISTINCT FROM COALESCE(m.evening_reminder_time, '18:00:00'::TIME)
    OR s.weekend_reminders IS DISTINCT FROM COALESCE(m.weekend_reminders, FALSE)
    OR s.email_notifications IS DISTINCT FROM COALESCE(m.email_notifications, FALSE)
    OR s.browser_notifications IS DISTINCT FROM COALESCE(m.browser_notifications, TRUE)
  );

ALTER TABLE public.daily_reports
  ALTER COLUMN id SET DEFAULT gen_random_uuid(),
  ALTER COLUMN user_id SET NOT NULL,
  ALTER COLUMN report_date SET NOT NULL,
  ALTER COLUMN report_type SET NOT NULL,
  ALTER COLUMN user_name_snapshot SET NOT NULL,
  ALTER COLUMN report_content SET NOT NULL,
  ALTER COLUMN created_at SET DEFAULT NOW(),
  ALTER COLUMN created_at SET NOT NULL,
  ALTER COLUMN updated_at SET DEFAULT NOW(),
  ALTER COLUMN updated_at SET NOT NULL;
ALTER TABLE public.draft_reports
  ALTER COLUMN id SET DEFAULT gen_random_uuid(),
  ALTER COLUMN user_id SET NOT NULL,
  ALTER COLUMN created_at SET DEFAULT NOW(),
  ALTER COLUMN created_at SET NOT NULL,
  ALTER COLUMN updated_at SET DEFAULT NOW(),
  ALTER COLUMN updated_at SET NOT NULL;
ALTER TABLE public.notification_settings
  ALTER COLUMN id SET DEFAULT gen_random_uuid(),
  ALTER COLUMN user_id SET NOT NULL,
  ALTER COLUMN morning_reminder_enabled SET DEFAULT TRUE,
  ALTER COLUMN morning_reminder_enabled SET NOT NULL,
  ALTER COLUMN morning_reminder_time SET DEFAULT '09:00:00',
  ALTER COLUMN morning_reminder_time SET NOT NULL,
  ALTER COLUMN evening_reminder_enabled SET DEFAULT TRUE,
  ALTER COLUMN evening_reminder_enabled SET NOT NULL,
  ALTER COLUMN evening_reminder_time SET DEFAULT '18:00:00',
  ALTER COLUMN evening_reminder_time SET NOT NULL,
  ALTER COLUMN weekend_reminders SET DEFAULT FALSE,
  ALTER COLUMN weekend_reminders SET NOT NULL,
  ALTER COLUMN email_notifications SET DEFAULT FALSE,
  ALTER COLUMN email_notifications SET NOT NULL,
  ALTER COLUMN browser_notifications SET DEFAULT TRUE,
  ALTER COLUMN browser_notifications SET NOT NULL,
  ALTER COLUMN created_at SET DEFAULT NOW(),
  ALTER COLUMN created_at SET NOT NULL,
  ALTER COLUMN updated_at SET DEFAULT NOW(),
  ALTER COLUMN updated_at SET NOT NULL;
ALTER TABLE public.notification_history
  ALTER COLUMN id SET DEFAULT gen_random_uuid(),
  ALTER COLUMN user_id SET NOT NULL,
  ALTER COLUMN notification_type SET NOT NULL,
  ALTER COLUMN title SET NOT NULL,
  ALTER COLUMN message SET NOT NULL,
  ALTER COLUMN is_read SET DEFAULT FALSE,
  ALTER COLUMN is_read SET NOT NULL,
  ALTER COLUMN sent_at SET DEFAULT NOW(),
  ALTER COLUMN sent_at SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'daily_reports_report_type_core_check') THEN
    ALTER TABLE public.daily_reports ADD CONSTRAINT daily_reports_report_type_core_check
      CHECK (report_type IN ('morning', 'evening', 'weekly')) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'draft_reports_report_type_core_check') THEN
    ALTER TABLE public.draft_reports ADD CONSTRAINT draft_reports_report_type_core_check
      CHECK (report_type IS NULL OR report_type IN ('morning', 'evening', 'weekly')) NOT VALID;
  END IF;
END $$;
ALTER TABLE public.daily_reports VALIDATE CONSTRAINT daily_reports_report_type_core_check;
ALTER TABLE public.draft_reports VALIDATE CONSTRAINT draft_reports_report_type_core_check;

DO $$
DECLARE
  table_name TEXT;
  constraint_name TEXT;
BEGIN
  FOR table_name, constraint_name IN
    SELECT * FROM (VALUES
      ('daily_reports', 'daily_reports_user_id_core_fkey'),
      ('draft_reports', 'draft_reports_user_id_core_fkey'),
      ('notification_settings', 'notification_settings_user_id_core_fkey'),
      ('notification_history', 'notification_history_user_id_core_fkey')
    ) AS table_constraints(table_name, constraint_name)
  LOOP
    IF NOT EXISTS (
      SELECT 1
      FROM pg_constraint c
      WHERE c.conrelid = format('public.%I', table_name)::regclass
        AND c.contype = 'f'
        AND c.confrelid = 'auth.users'::regclass
    ) THEN
      EXECUTE format(
        'ALTER TABLE public.%I ADD CONSTRAINT %I FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE NOT VALID',
        table_name, constraint_name
      );
    END IF;
  END LOOP;
END $$;

DO $$
DECLARE
  table_name TEXT;
  constraint_name TEXT;
BEGIN
  FOR table_name, constraint_name IN
    SELECT * FROM (VALUES
      ('daily_reports', 'daily_reports_user_id_core_fkey'),
      ('draft_reports', 'draft_reports_user_id_core_fkey'),
      ('notification_settings', 'notification_settings_user_id_core_fkey'),
      ('notification_history', 'notification_history_user_id_core_fkey')
    ) AS table_constraints(table_name, constraint_name)
  LOOP
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = constraint_name) THEN
      EXECUTE format('ALTER TABLE public.%I VALIDATE CONSTRAINT %I', table_name, constraint_name);
    END IF;
  END LOOP;
END $$;

DO $$
DECLARE
  table_name TEXT;
  index_name TEXT;
  constraint_name TEXT;
BEGIN
  FOR table_name, index_name, constraint_name IN
    SELECT * FROM (VALUES
      ('daily_reports', 'daily_reports_id_core_unique', 'daily_reports_pkey_core'),
      ('draft_reports', 'draft_reports_id_core_unique', 'draft_reports_pkey_core'),
      ('notification_settings', 'notification_settings_id_core_unique', 'notification_settings_pkey_core'),
      ('notification_history', 'notification_history_id_core_unique', 'notification_history_pkey_core')
    ) AS table_constraints(table_name, index_name, constraint_name)
  LOOP
    EXECUTE format('CREATE UNIQUE INDEX IF NOT EXISTS %I ON public.%I(id)', index_name, table_name);
    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint
      WHERE conrelid = format('public.%I', table_name)::regclass AND contype = 'p'
    ) THEN
      EXECUTE format('ALTER TABLE public.%I ADD CONSTRAINT %I PRIMARY KEY USING INDEX %I', table_name, constraint_name, index_name);
    END IF;
  END LOOP;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    JOIN pg_index i ON i.indexrelid = c.oid
    WHERE n.nspname = 'public' AND c.relname = 'idx_notification_settings_user_id' AND NOT i.indisunique
  ) THEN
    DROP INDEX public.idx_notification_settings_user_id;
  END IF;
END $$;
CREATE UNIQUE INDEX IF NOT EXISTS idx_notification_settings_user_id
  ON public.notification_settings(user_id);

ALTER TABLE public.daily_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.draft_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_history ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.core_product_migration_quarantine FROM anon, PUBLIC, authenticated;
GRANT ALL ON TABLE public.core_product_migration_quarantine TO service_role;
REVOKE ALL ON TABLE public.daily_reports, public.draft_reports, public.notification_settings, public.notification_history FROM anon, PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.daily_reports, public.draft_reports, public.notification_settings, public.notification_history TO authenticated;
GRANT ALL ON TABLE public.daily_reports, public.draft_reports, public.notification_settings, public.notification_history TO service_role;
CREATE OR REPLACE FUNCTION public.handle_new_user_notification_settings()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  INSERT INTO public.notification_settings(user_id)
  VALUES (NEW.id)
  ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END
$$;
REVOKE ALL ON FUNCTION public.core_product_set_updated_at() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.handle_new_user_notification_settings() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.core_product_set_updated_at() TO service_role;
GRANT EXECUTE ON FUNCTION public.handle_new_user_notification_settings() TO service_role;
