'use client';

import '@ant-design/v5-patch-for-react-19'; // Ant Design React 19 호환성 패치 임포트
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/ThemeProvider";
import { AuthProvider } from "@/context/AuthContext";
import { App as AntApp } from 'antd'; // Ant Design의 App 컴포넌트 임포트

const inter = Inter({ subsets: ["latin"] });

// Metadata는 서버 컴포넌트에서만 사용 가능하므로, 'use client' 환경에서는 직접 정의하지 않거나 다른 방식을 사용해야 합니다.
// 우선은 주석 처리하거나 제거합니다. 필요하다면 App Router의 generateMetadata 함수를 사용합니다.
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
            <AntApp>
              <main style={{ padding: '0' }}>{children}</main>
            </AntApp>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
